In [1]:
## embedding fun

In [2]:
import torch 

In [3]:
C  = torch.randn((27,2))
C

tensor([[-0.1339,  1.2147],
        [-0.3807, -1.1200],
        [-1.4080,  0.0745],
        [-1.4607,  0.8900],
        [-0.1339,  1.3353],
        [ 0.5446,  0.1702],
        [ 0.5083, -0.3215],
        [-1.4308, -0.1045],
        [-0.8188, -0.1936],
        [-0.3421, -0.5028],
        [ 0.6189, -0.3500],
        [-0.3887,  0.4577],
        [ 1.7861, -1.4745],
        [ 1.1787,  1.1959],
        [ 3.1037,  0.4426],
        [ 0.3827, -0.9030],
        [ 0.3387, -1.1631],
        [ 0.3210,  1.0481],
        [ 0.4876, -0.0162],
        [-0.0774, -1.0157],
        [ 0.0488, -2.1364],
        [ 0.9333, -1.0443],
        [ 0.4161, -0.5762],
        [-0.1170,  0.6914],
        [ 0.1455,  1.8207],
        [ 2.0566,  1.2015],
        [-0.2852, -1.7131]])

In [9]:
ds = torch.randn((32, 3))
ds.long()

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  1,  0],
        [ 0,  0,  0],
        [-1,  0, -1],
        [ 0,  1,  1],
        [ 0,  0,  0],
        [-1,  0,  0],
        [ 0,  1,  0],
        [ 0,  0,  2],
        [ 1, -1,  0],
        [ 0,  0,  0],
        [ 0,  1,  1],
        [ 1,  0,  0],
        [ 0,  0,  0],
        [-1,  1,  0],
        [-1,  0,  1],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0, -1],
        [-1,  0,  0],
        [ 0,  0,  1],
        [ 0,  0,  0],
        [ 0, -1, -1],
        [ 0,  0,  0],
        [ 0,  0, -1],
        [ 0,  0,  0],
        [-1,  0,  0],
        [ 0, -2,  0],
        [ 0,  0,  0],
        [ 0,  1,  0],
        [ 0,  1, -1]])

tensor([[[-0.1339,  1.2147],
         [-0.1339,  1.2147],
         [-0.1339,  1.2147]],

        [[-0.1339,  1.2147],
         [-0.1339,  1.2147],
         [-0.1339,  1.2147]],

        [[-0.1339,  1.2147],
         [-0.3807, -1.1200],
         [-0.1339,  1.2147]],

        [[-0.1339,  1.2147],
         [-0.1339,  1.2147],
         [-0.1339,  1.2147]],

        [[-0.2852, -1.7131],
         [-0.1339,  1.2147],
         [-0.2852, -1.7131]],

        [[-0.1339,  1.2147],
         [-0.3807, -1.1200],
         [-0.3807, -1.1200]],

        [[-0.1339,  1.2147],
         [-0.1339,  1.2147],
         [-0.1339,  1.2147]],

        [[-0.2852, -1.7131],
         [-0.1339,  1.2147],
         [-0.1339,  1.2147]],

        [[-0.1339,  1.2147],
         [-0.3807, -1.1200],
         [-0.1339,  1.2147]],

        [[-0.1339,  1.2147],
         [-0.1339,  1.2147],
         [-1.4080,  0.0745]],

        [[-0.3807, -1.1200],
         [-0.2852, -1.7131],
         [-0.1339,  1.2147]],

        [[-0.1339,  1

In [17]:
C[1][0]

tensor(-0.3807)